/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Noah Cummings, Ivan Lin, Logan Sevatzian
 */
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JPanel;
public class adminHome extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form adminHome
     */
    public adminHome(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPeriod = new javax.swing.JComboBox<>();
        lblPeriod = new javax.swing.JLabel();
        btnIncomingOrders = new javax.swing.JButton();
        btnCompleteOrders = new javax.swing.JButton();
        btnEditMenu = new javax.swing.JButton();
        btnClearAllOrders = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cbxPeriod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cbxPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cbxPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeriodActionPerformed(evt);
            }
        });

        lblPeriod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPeriod.setText("Period : ");

        btnIncomingOrders.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnIncomingOrders.setText("Incoming Orders");
        btnIncomingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomingOrdersActionPerformed(evt);
            }
        });

        btnCompleteOrders.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnCompleteOrders.setText("Complete Orders");
        btnCompleteOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteOrdersActionPerformed(evt);
            }
        });

        btnEditMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnEditMenu.setText("Edit Menu");
        btnEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMenuActionPerformed(evt);
            }
        });

        btnClearAllOrders.setText("Clear All Orders");
        btnClearAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearAllOrders)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeriod)
                        .addGap(27, 27, 27)
                        .addComponent(cbxPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCompleteOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIncomingOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClearAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriod)
                    .addComponent(cbxPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnIncomingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnCompleteOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnIncomingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomingOrdersActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "incomingOrders");
    }//GEN-LAST:event_btnIncomingOrdersActionPerformed

    private void btnCompleteOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteOrdersActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "completeOrders");
    }//GEN-LAST:event_btnCompleteOrdersActionPerformed

    private void btnEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMenuActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "editMenu");
    }//GEN-LAST:event_btnEditMenuActionPerformed

    private void btnClearAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllOrdersActionPerformed
        orders.clear();
        
        try{
            BufferedWriter writer = new BufferedWriter(new FileWriter("src/orders.txt"));
            writer.write("");
            writer.close();
        } catch (Exception e){

        }
        
        try {
            register.AccountFile.createNewFile();
            try (BufferedWriter deleter = new BufferedWriter(new FileWriter(register.AccountFile.getAbsolutePath()))){
                deleter.write("");
                deleter.close();
                BufferedWriter writer = new BufferedWriter(new FileWriter(register.AccountFile.getAbsolutePath(), true));

                for (int index = 0; index < register.AccountList.size(); index++) {
                    String writeLine = "";
                    writeLine += register.AccountList.get(index).getEmail() + ",";
                    writeLine += register.AccountList.get(index).getPassword() + ",";
                    writeLine += register.AccountList.get(index).getCardNumber() + ",";
                    writeLine += register.AccountList.get(index).getSecurityCode() + ",";
                    writeLine += register.AccountList.get(index).getPoints() + "\n";
                    writer.append(writeLine);
                }
                writer.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnClearAllOrdersActionPerformed
    
    static ArrayList <Order> orders = new ArrayList <Order>();
    static int period = 2;
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        refresh();
    }//GEN-LAST:event_formComponentShown

    private void cbxPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeriodActionPerformed
        period = cbxPeriod.getSelectedIndex()+2;
    }//GEN-LAST:event_cbxPeriodActionPerformed
    
    public static void refresh(){
        try{
            BufferedReader reader = new BufferedReader(new FileReader("src/orders.txt"));
                String line;
                orders.clear();
                while((line = reader.readLine()) != null){
                    String[] order = line.split(",");
                    int orderID = Integer.parseInt(order[0]);
                    int period = Integer.parseInt(order[1]);
                    int status = Integer.parseInt(order[2]);
                    double cost = Double.parseDouble(order[3]);
                    ArrayList<Item> items = new ArrayList<Item>();
                    for(int i = 4; i < order.length; i+=3){
                        String itemName = order[i];
                        int itemQuantity = Integer.parseInt(order[i+1]);
                        double itemCost = Double.parseDouble(order[i+2]);
                        
                        items.add(new Item(itemName, itemQuantity, itemCost));
                    }
                    
                    orders.add(new Order(orderID, period, status, cost, items));
                    
                }
        } catch (Exception e){
            //e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAllOrders;
    private javax.swing.JButton btnCompleteOrders;
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnIncomingOrders;
    private javax.swing.JComboBox<String> cbxPeriod;
    private javax.swing.JLabel lblPeriod;
    // End of variables declaration//GEN-END:variables
}
