/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author noahc
 */
import java.awt.CardLayout;
import javax.swing.JPanel;
public class adminHome extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form adminHome
     */
    public adminHome(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPeriod = new javax.swing.JComboBox<>();
        lblPeriod = new javax.swing.JLabel();
        btnIncomingOrders = new javax.swing.JButton();
        btnCompleteOrders = new javax.swing.JButton();
        btnEditMenu = new javax.swing.JButton();
        btnClearAllOrders = new javax.swing.JButton();

        cbxPeriod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        cbxPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));

        lblPeriod.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPeriod.setText("Period : ");

        btnIncomingOrders.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnIncomingOrders.setText("Incoming Orders");
        btnIncomingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomingOrdersActionPerformed(evt);
            }
        });

        btnCompleteOrders.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnCompleteOrders.setText("Complete Orders");
        btnCompleteOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteOrdersActionPerformed(evt);
            }
        });

        btnEditMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnEditMenu.setText("Edit Menu");
        btnEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMenuActionPerformed(evt);
            }
        });

        btnClearAllOrders.setText("Clear All Orders");
        btnClearAllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearAllOrders)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeriod)
                        .addGap(27, 27, 27)
                        .addComponent(cbxPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCompleteOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIncomingOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClearAllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriod)
                    .addComponent(cbxPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnIncomingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnCompleteOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncomingOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomingOrdersActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "incomingOrders");
    }//GEN-LAST:event_btnIncomingOrdersActionPerformed

    private void btnCompleteOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteOrdersActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "completeOrders");
    }//GEN-LAST:event_btnCompleteOrdersActionPerformed

    private void btnEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMenuActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "editMenu");
    }//GEN-LAST:event_btnEditMenuActionPerformed

    private void btnClearAllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearAllOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAllOrders;
    private javax.swing.JButton btnCompleteOrders;
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnIncomingOrders;
    private javax.swing.JComboBox<String> cbxPeriod;
    private javax.swing.JLabel lblPeriod;
    // End of variables declaration//GEN-END:variables
}
