
import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Noah Cummings, Ivan Lin, Logan Sevatzian
 */
public class completeOrders extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form completeOrders
     */
    public completeOrders(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_completeOrders = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpOrder = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_completeOrders = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        lblOrder = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lbl_completeOrders.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        lbl_completeOrders.setText("Complete Orders");

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        txpOrder.setEditable(false);
        txpOrder.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txpOrder);

        lst_completeOrders.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_completeOrdersValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lst_completeOrders);

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblOrder.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        lblOrder.setText("Order");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lbl_completeOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemove))
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(lblOrder))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_completeOrders)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "adminHome");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int index = lst_completeOrders.getSelectedIndex();
        index = BinarySearch.binarySearch(adminHome.orders, completeOrders.get(index), 0, adminHome.orders.size()-1);
        adminHome.orders.get(index).setStatus(0);
        
        try{
            BufferedWriter writer = new BufferedWriter(new FileWriter("src/orders.txt"));
            writer.write(adminHome.orders.get(0).toString());
            for(int i = 1; i < adminHome.orders.size(); i++){
                writer.write("\n" + (adminHome.orders.get(i).toString()));
            }
            writer.close();
        } catch (Exception e){

        }
        
        adminHome.refresh();
        
        completeOrders.clear();
        for(int i = 0; i < adminHome.orders.size(); i++){
            if(adminHome.orders.get(i).getPeriod() == adminHome.period 
               && adminHome.orders.get(i).getStatusInt() > 0){
                completeOrders.add(adminHome.orders.get(i));
            }
        }
        
        String[] lstOutput = new String[completeOrders.size()];
        for(int i = 0; i < completeOrders.size(); i++){
            lstOutput[i] = Integer.toString(completeOrders.get(i).getOrderID());
        }
        lst_completeOrders.setListData(lstOutput);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        adminHome.refresh();
        
        completeOrders.clear();
        for(int i = 0; i < adminHome.orders.size(); i++){
            if(adminHome.orders.get(i).getPeriod() == adminHome.period 
               && adminHome.orders.get(i).getStatusInt() > 0){
                completeOrders.add(adminHome.orders.get(i));
            }
        }
        
        String[] lstOutput = new String[completeOrders.size()];
        for(int i = 0; i < completeOrders.size(); i++){
            lstOutput[i] = Integer.toString(completeOrders.get(i).getOrderID());
        }
        lst_completeOrders.setListData(lstOutput);
    }//GEN-LAST:event_btnRefreshActionPerformed
    
    ArrayList <Order> completeOrders = new ArrayList <Order>();
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        completeOrders.clear();
        for(int i = 0; i < adminHome.orders.size(); i++){
            if(adminHome.orders.get(i).getPeriod() == adminHome.period 
               && adminHome.orders.get(i).getStatusInt() > 0){
                completeOrders.add(adminHome.orders.get(i));
            }
        }
        
        String[] lstOutput = new String[completeOrders.size()];
        for(int i = 0; i < completeOrders.size(); i++){
            lstOutput[i] = Integer.toString(completeOrders.get(i).getOrderID());
        }
        lst_completeOrders.setListData(lstOutput);
    }//GEN-LAST:event_formComponentShown

    private void lst_completeOrdersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_completeOrdersValueChanged
        int index = lst_completeOrders.getSelectedIndex();
        if(index != -1){
            Order order = completeOrders.get(index);
            ArrayList <Item> items = order.getItems();
            String strItems = "";
            for(int i = 0; i < items.size(); i++){
                Item item = items.get(i);
                strItems += "\n  x" + item.getQuantity() + " " + item.getName() + ", " + item.getCost();
            }

            String strOutput = "Order ID : " + order.getOrderID() +
                             "\nPeriod : " + order.getPeriod() + 
                             "\nStatus : " + order.getStatusString() + 
                             "\nCost : " + order.getCost() + 
                             "\nItems : " + strItems;
            txpOrder.setText(strOutput);
        } else {
            txpOrder.setText("");
        }
    }//GEN-LAST:event_lst_completeOrdersValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lbl_completeOrders;
    private javax.swing.JList<String> lst_completeOrders;
    private javax.swing.JTextPane txpOrder;
    // End of variables declaration//GEN-END:variables
}
