
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ivanlin
 */
public class customerHomeScreen extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form customerHomeScreen
     */
    public customerHomeScreen(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_logo2 = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        icon_gradient1 = new javax.swing.JLabel();
        lbl_currentOrders = new javax.swing.JLabel();
        lbl_newOrder = new javax.swing.JLabel();
        btn_newOrder = new javax.swing.JButton();
        pane_orderDisplay = new javax.swing.JScrollPane();
        txt_orderDisplay = new javax.swing.JTextArea();

        setLayout(null);

        icon_logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quick_bite_logo_80x80.png"))); // NOI18N
        add(icon_logo2);
        icon_logo2.setBounds(0, 0, 80, 80);

        lbl_title2.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lbl_title2.setText("Quick Bite");
        add(lbl_title2);
        lbl_title2.setBounds(140, 20, 110, 29);

        icon_gradient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalGradient.png"))); // NOI18N
        add(icon_gradient1);
        icon_gradient1.setBounds(0, 0, 370, 80);

        lbl_currentOrders.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_currentOrders.setText("Current Orders:");
        add(lbl_currentOrders);
        lbl_currentOrders.setBounds(120, 100, 140, 20);

        lbl_newOrder.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_newOrder.setText("New Order:");
        add(lbl_newOrder);
        lbl_newOrder.setBounds(130, 310, 110, 22);

        btn_newOrder.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btn_newOrder.setText("Place new order");
        add(btn_newOrder);
        btn_newOrder.setBounds(110, 340, 140, 40);

        txt_orderDisplay.setColumns(20);
        txt_orderDisplay.setRows(5);
        pane_orderDisplay.setViewportView(txt_orderDisplay);

        add(pane_orderDisplay);
        pane_orderDisplay.setBounds(60, 130, 270, 160);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newOrder;
    private javax.swing.JLabel icon_gradient1;
    private javax.swing.JLabel icon_logo2;
    private javax.swing.JLabel lbl_currentOrders;
    private javax.swing.JLabel lbl_newOrder;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JScrollPane pane_orderDisplay;
    private javax.swing.JTextArea txt_orderDisplay;
    // End of variables declaration//GEN-END:variables
}
