
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ivanlin
 */
public class customerHomeScreen extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form customerHomeScreen
     */
    public customerHomeScreen(JPanel mainPanel) {
        this.mainPanel = mainPanel;        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_logo2 = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        lbl_loggedInAs = new javax.swing.JLabel();
        icon_gradient1 = new javax.swing.JLabel();
        lbl_currentOrders = new javax.swing.JLabel();
        lbl_newOrder = new javax.swing.JLabel();
        btn_newOrder = new javax.swing.JButton();
        pane_orderDisplay = new javax.swing.JScrollPane();
        txt_orderDisplay = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);

        icon_logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quick_bite_logo_80x80.png"))); // NOI18N
        add(icon_logo2);
        icon_logo2.setBounds(0, 0, 80, 80);

        lbl_title2.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lbl_title2.setText("Quick Bite");
        add(lbl_title2);
        lbl_title2.setBounds(140, 20, 130, 30);

        lbl_loggedInAs.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lbl_loggedInAs.setText("Logged in as: ");
        add(lbl_loggedInAs);
        lbl_loggedInAs.setBounds(140, 40, 210, 30);

        icon_gradient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalGradient.png"))); // NOI18N
        add(icon_gradient1);
        icon_gradient1.setBounds(0, 0, 370, 80);

        lbl_currentOrders.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_currentOrders.setText("Current Quick Bite Orders:");
        add(lbl_currentOrders);
        lbl_currentOrders.setBounds(60, 100, 240, 20);

        lbl_newOrder.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_newOrder.setText("New Order:");
        add(lbl_newOrder);
        lbl_newOrder.setBounds(130, 390, 110, 22);

        btn_newOrder.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        btn_newOrder.setText("Place new order");
        btn_newOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newOrderActionPerformed(evt);
            }
        });
        add(btn_newOrder);
        btn_newOrder.setBounds(120, 420, 130, 40);

        txt_orderDisplay.setColumns(20);
        txt_orderDisplay.setRows(5);
        pane_orderDisplay.setViewportView(txt_orderDisplay);

        add(pane_orderDisplay);
        pane_orderDisplay.setBounds(0, 130, 370, 240);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh);
        btnRefresh.setBounds(290, 375, 75, 23);
    }// </editor-fold>//GEN-END:initComponents

    ArrayList <Order> orders = new ArrayList <Order>();
    
    private void btn_newOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newOrderActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "newOrder");
    }//GEN-LAST:event_btn_newOrderActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        lbl_loggedInAs.setText("Logged in as: " + register.CurrentUser.getEmail());
        
        orders = register.CurrentUser.get
    }//GEN-LAST:event_formComponentShown

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        refresh();
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    public void refresh(){
        try{
            BufferedReader reader = new BufferedReader(new FileReader("src/orders.txt"));
                String line;
                while((line = reader.readLine()) != null){
                    String[] order = line.split(",");
                    int orderID = Integer.parseInt(order[0]);
                    int period = Integer.parseInt(order[1]);
                    int status = Integer.parseInt(order[2]);
                    double cost = Double.parseDouble(order[3]);
                    ArrayList<Item> items = new ArrayList<Item>();
                    for(int i = 4; i < order.length; i+=3){
                        String itemName = order[i];
                        int itemQuantity = Integer.parseInt(order[i+1]);
                        double itemCost = Double.parseDouble(order[i+2]);
                        
                        items.add(new Item(itemName, itemQuantity, itemCost));
                    }
                    
                    orders.add(new Order(orderID, period, status, cost, items));
                    
                }
        } catch (Exception e){
            //e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btn_newOrder;
    private javax.swing.JLabel icon_gradient1;
    private javax.swing.JLabel icon_logo2;
    private javax.swing.JLabel lbl_currentOrders;
    private javax.swing.JLabel lbl_loggedInAs;
    private javax.swing.JLabel lbl_newOrder;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JScrollPane pane_orderDisplay;
    private javax.swing.JTextArea txt_orderDisplay;
    // End of variables declaration//GEN-END:variables
}
