
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ivanlin
 */
public class incomingOrders extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form IncomingOrders
     */
    public incomingOrders(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_incomingOrders = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_incomingOrders = new javax.swing.JList<>();
        lblOrder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpOrder = new javax.swing.JTextPane();
        btnBack = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lbl_incomingOrders.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        lbl_incomingOrders.setText("Incoming Orders");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lst_incomingOrders.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " ", " ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lst_incomingOrders.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_incomingOrders.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_incomingOrdersValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lst_incomingOrders);

        lblOrder.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        lblOrder.setText("Order");

        jScrollPane1.setViewportView(txpOrder);

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnComplete.setText("Mark As Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lbl_incomingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnComplete))
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(lblOrder))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl_incomingOrders)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnComplete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        adminHome.refresh();
        
        for(int i = 0; i < adminHome.orders.size(); i++){
            if(adminHome.orders.get(i).getPeriod() == adminHome.period){
                incomingOrders.add(adminHome.orders.get(i));
            }
        }
        
        String[] lstOutput = new String[incomingOrders.size()];
        for(int i = 0; i < incomingOrders.size(); i++){
            lstOutput[i] = Integer.toString(incomingOrders.get(i).getOrderID());
        }
        lst_incomingOrders.setListData(lstOutput);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "adminHome");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        int index = lst_incomingOrders.getSelectedIndex();
        index = BinarySearch.binarySearch(adminHome.orders, incomingOrders.get(index), 0, adminHome.orders.size()-1);
        adminHome.orders.get(index).setStatus(1);
        
        
        
    }//GEN-LAST:event_btnCompleteActionPerformed
    
    ArrayList <Order> incomingOrders = new ArrayList <Order>();
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        for(int i = 0; i < adminHome.orders.size(); i++){
            if(adminHome.orders.get(i).getPeriod() == adminHome.period 
               && adminHome.orders.get(i).getStatusInt() < 0){
                incomingOrders.add(adminHome.orders.get(i));
            }
        }
        
        String[] lstOutput = new String[incomingOrders.size()];
        for(int i = 0; i < incomingOrders.size(); i++){
            lstOutput[i] = Integer.toString(incomingOrders.get(i).getOrderID());
        }
        lst_incomingOrders.setListData(lstOutput);
    }//GEN-LAST:event_formComponentShown

    private void lst_incomingOrdersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lst_incomingOrdersValueChanged
        int index = lst_incomingOrders.getSelectedIndex();
        Order order = incomingOrders.get(index);
        ArrayList <Item> items = order.getItems();
        String strItems = "";
        for(int i = 0; i < items.size(); i++){
            Item item = items.get(i);
            strItems += "\n  x" + item.getQuantity() + " " + item.getName() + ", " + item.getCost();
        }
        
        String txpOutput = "Order ID : " + order.getOrderID() +
                         "\nPeriod : " + order.getPeriod() + 
                         "\nStatus : " + order.getStatusString() + 
                         "\nCost : " + order.getCost() + 
                         "\nItems : " + strItems + "\n\n";
        txpOrder.setText(strItems);
    }//GEN-LAST:event_lst_incomingOrdersValueChanged
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lbl_incomingOrders;
    private javax.swing.JList<String> lst_incomingOrders;
    private javax.swing.JTextPane txpOrder;
    // End of variables declaration//GEN-END:variables
}
