
import java.awt.CardLayout;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ivanlin
 */
public class login extends javax.swing.JPanel {
    JPanel mainPanel;
    /**
     * Creates new form login
     */
    public login(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_registerPrompt = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_companyTitle = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_login = new javax.swing.JLabel();
        txt_loginType = new javax.swing.JComboBox<>();
        btn_toRegisterScreen = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();

        setLayout(null);

        lbl_registerPrompt.setText("New user?");
        add(lbl_registerPrompt);
        lbl_registerPrompt.setBounds(120, 350, 60, 16);

        btn_login.setText("Login");
        add(btn_login);
        btn_login.setBounds(150, 310, 60, 23);

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoReal.png"))); // NOI18N
        add(icon_logo);
        icon_logo.setBounds(0, 0, 80, 80);

        lbl_title.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_title.setText("Quick Bite");
        add(lbl_title);
        lbl_title.setBounds(150, 10, 80, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueskibidigradient.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 370, 80);
        add(txt_email);
        txt_email.setBounds(110, 190, 214, 30);

        lbl_companyTitle.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle.setText("Ivan's Z's Inc.");
        add(lbl_companyTitle);
        lbl_companyTitle.setBounds(140, 40, 100, 22);
        add(txt_password);
        txt_password.setBounds(110, 260, 214, 30);

        lbl_login.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Login");
        add(lbl_login);
        lbl_login.setBounds(100, 90, 170, 38);

        txt_loginType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Administrator" }));
        add(txt_loginType);
        txt_loginType.setBounds(110, 150, 214, 22);

        btn_toRegisterScreen.setForeground(new java.awt.Color(0, 0, 255));
        btn_toRegisterScreen.setText("Register an account");
        btn_toRegisterScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_toRegisterScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_toRegisterScreenMouseClicked(evt);
            }
        });
        add(btn_toRegisterScreen);
        btn_toRegisterScreen.setBounds(180, 350, 110, 16);

        lbl_password.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText("Password:");
        add(lbl_password);
        lbl_password.setBounds(24, 260, 80, 22);

        lbl_email.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email.setText("Email:");
        add(lbl_email);
        lbl_email.setBounds(53, 190, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_toRegisterScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_toRegisterScreenMouseClicked
        //When user clicks the prompt on the login screen, this takes them to the register screen
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "register");
    }//GEN-LAST:event_btn_toRegisterScreenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_toRegisterScreen;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_companyTitle;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_registerPrompt;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox<String> txt_loginType;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
