/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author noahc
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_login = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        txt_loginType = new javax.swing.JComboBox<>();
        icon_logo = new javax.swing.JLabel();
        lbl_companyTitle = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_login.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Login");
        getContentPane().add(lbl_login);
        lbl_login.setBounds(100, 90, 170, 38);

        lbl_email.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email.setText("Email:");
        getContentPane().add(lbl_email);
        lbl_email.setBounds(53, 190, 50, 30);
        getContentPane().add(txt_email);
        txt_email.setBounds(110, 190, 214, 30);

        lbl_password.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText("Password:");
        getContentPane().add(lbl_password);
        lbl_password.setBounds(24, 260, 80, 22);
        getContentPane().add(txt_password);
        txt_password.setBounds(110, 260, 214, 30);

        txt_loginType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Administrator" }));
        getContentPane().add(txt_loginType);
        txt_loginType.setBounds(110, 150, 214, 22);

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoReal.png"))); // NOI18N
        getContentPane().add(icon_logo);
        icon_logo.setBounds(0, 0, 80, 80);

        lbl_companyTitle.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle.setText("Ivan's Z's Inc.");
        getContentPane().add(lbl_companyTitle);
        lbl_companyTitle.setBounds(140, 40, 100, 22);

        lbl_title.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_title.setText("Quick Bite");
        getContentPane().add(lbl_title);
        lbl_title.setBounds(150, 10, 80, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueskibidigradient.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 370, 80);

        btn_login.setText("Login");
        getContentPane().add(btn_login);
        btn_login.setBounds(150, 310, 60, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_companyTitle;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox<String> txt_loginType;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
