
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author noahc
 */
import javax.swing.JOptionPane;
import java.io.*;

public class login extends javax.swing.JPanel {
    JPanel mainPanel;
    /**
     * Creates new form login
     */
    public login(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_registerPrompt = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        icon_logo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_companyTitle = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_login = new javax.swing.JLabel();
        txt_loginType = new javax.swing.JComboBox<>();
        btn_toRegisterScreen = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();

        setLayout(null);

        lbl_title.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lbl_title.setText("Quick Bite");
        add(lbl_title);
        lbl_title.setBounds(130, 25, 130, 30);

        lbl_registerPrompt.setText("New user?");
        add(lbl_registerPrompt);
        lbl_registerPrompt.setBounds(90, 400, 70, 17);

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        add(btn_login);
        btn_login.setBounds(150, 360, 70, 23);

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quick_bite_logo_80x80.png"))); // NOI18N
        add(icon_logo);
        icon_logo.setBounds(0, 0, 80, 80);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalGradient.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 370, 80);
        add(txt_email);
        txt_email.setBounds(80, 240, 214, 30);

        lbl_companyTitle.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle.setText("Ivan's Z's Inc.");
        add(lbl_companyTitle);
        lbl_companyTitle.setBounds(140, 40, 100, 22);
        add(txt_password);
        txt_password.setBounds(80, 310, 214, 30);

        lbl_login.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Login");
        add(lbl_login);
        lbl_login.setBounds(100, 130, 170, 38);

        txt_loginType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Administrator" }));
        add(txt_loginType);
        txt_loginType.setBounds(80, 180, 214, 23);

        btn_toRegisterScreen.setForeground(new java.awt.Color(0, 0, 255));
        btn_toRegisterScreen.setText("Register an account");
        btn_toRegisterScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_toRegisterScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_toRegisterScreenMouseClicked(evt);
            }
        });
        add(btn_toRegisterScreen);
        btn_toRegisterScreen.setBounds(160, 400, 130, 17);

        lbl_password.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText("Password");
        add(lbl_password);
        lbl_password.setBounds(80, 280, 81, 22);

        lbl_email.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email.setText("Email");
        add(lbl_email);
        lbl_email.setBounds(80, 210, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    static int userIndex = -1;
    
    private void btn_toRegisterScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_toRegisterScreenMouseClicked
        //When user clicks the prompt on the login screen, this takes them to the register screen
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "register");
    }//GEN-LAST:event_btn_toRegisterScreenMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        //Filling in account list arraylist
        if (register.AccountList.isEmpty()) {
            readFile();
        }

        //Validating input fields
        //Checking for empty fields
        if (txt_email.getText().strip().isEmpty() || txt_password.getText().strip().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please ensure an email and password have been entered.", "Warning!", 2);
        } else {
            BinarySearch search = new BinarySearch();
            if (search.search(register.AccountList, txt_email.getText().strip()) || txt_email.getText().strip().equalsIgnoreCase("admin")) { //Checking if the email maps to a registered email
               boolean loginSuccess = false; 
               for (int i = 0; i < register.AccountList.size(); i++) {
                   if (register.AccountList.get(i).getEmail().equalsIgnoreCase(txt_email.getText().strip()) && register.AccountList.get(i).getPassword().equals(txt_password.getText().strip())) {
                       loginSuccess = true;
                       userIndex = i;
                       register.CurrentUser = register.AccountList.get(i);
                       JOptionPane.showMessageDialog(this, "Login success!");
                       
                       //Sending user to homescreen
                       CardLayout cl = (CardLayout) mainPanel.getLayout();
                       cl.show(mainPanel, "customerHomeScreen");
                   }
               } 
               if (loginSuccess == false) {
                   if (txt_email.getText().strip().equalsIgnoreCase("admin") && txt_password.getText().strip().equals("khurramrulez") && txt_loginType.getSelectedItem().toString().equals("Administrator")) {
                       //Sending user to admin screen
                       CardLayout cl = (CardLayout) mainPanel.getLayout();
                       cl.show(mainPanel, "adminHome");
                   } else {
                       JOptionPane.showMessageDialog(this, "The email or password entered is incorrect.");
                   }
               }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a registered email.", "Error", 2);
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed
    
    File AccountFile = new File("Accounts.txt");
    public void readFile() { //Method for reading from the text file, and converting the raw data into customer instances
        try {
            if (!AccountFile.createNewFile()) { //If the account fails to create (Already existing), read from the file
                BufferedReader reader = new BufferedReader(new FileReader(AccountFile.getAbsoluteFile()));
                String line;
                
                while ((line = reader.readLine()) != null) {
                    String[] lineArray = line.split(","); //Splitting everything by commas
                    String email = lineArray[0];
                    String password = lineArray[1];
                    String cardNumber = lineArray[2];
                    String cvv = lineArray[3];
                    int points = Integer.parseInt(lineArray[4]);
                    
                    Customer person = new Customer(email, password, cardNumber, cvv); //Constructor only takes these values
                    person.addPoints(points); //Adding customer's points to the default balance of zero
                    register.AccountList.add(person);
                }
                reader.close();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fatal error reading from accounts file. " + e, "ERROR!", 2);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_toRegisterScreen;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_companyTitle;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_registerPrompt;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_email;
    private javax.swing.JComboBox<String> txt_loginType;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
