/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @authors Noah Cummings, Ivan Lin, Logan Sevatzian
 */
import javax.swing.JOptionPane;
import java.io.*;
import java.util.ArrayList;
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form LoginFrame
     */
    public MainFrame() {
        initComponents();
        pnl_login.setVisible(true);
        pnl_register.setVisible(false);
        pnl_customerHomeScreen.setVisible(false);
        pnl_adminHomeScreen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_register = new javax.swing.JPanel();
        lbl_email1 = new javax.swing.JLabel();
        txt_email1 = new javax.swing.JTextField();
        lbl_register = new javax.swing.JLabel();
        txt_password1 = new javax.swing.JTextField();
        lbl_password1 = new javax.swing.JLabel();
        icon_logo1 = new javax.swing.JLabel();
        lbl_companyTitle1 = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        icon_gradient = new javax.swing.JLabel();
        lbl_cardNumber = new javax.swing.JLabel();
        lbl_cvv = new javax.swing.JLabel();
        txt_cardNumber = new javax.swing.JTextField();
        txt_cvv = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        lbl_loginPrompt = new javax.swing.JLabel();
        btn_toLoginScreen = new javax.swing.JLabel();
        pnl_login = new javax.swing.JPanel();
        lbl_registerPrompt = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_companyTitle = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_login = new javax.swing.JLabel();
        txt_loginType = new javax.swing.JComboBox<>();
        btn_toRegisterScreen = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        pnl_customerHomeScreen = new javax.swing.JPanel();
        icon_logo2 = new javax.swing.JLabel();
        lbl_companyTitle2 = new javax.swing.JLabel();
        lbl_title2 = new javax.swing.JLabel();
        icon_gradient1 = new javax.swing.JLabel();
        lbl_currentOrders = new javax.swing.JLabel();
        lbl_newOrder = new javax.swing.JLabel();
        btn_newOrder = new javax.swing.JButton();
        pane_orderDisplay = new javax.swing.JScrollPane();
        txt_orderDisplay = new javax.swing.JTextArea();
        pnl_adminHomeScreen = new javax.swing.JPanel();
        icon_logo3 = new javax.swing.JLabel();
        lbl_companyTitle3 = new javax.swing.JLabel();
        lbl_title3 = new javax.swing.JLabel();
        icon_gradient2 = new javax.swing.JLabel();
        lbl_incomingOrders = new javax.swing.JLabel();
        pane_incomingOrders = new javax.swing.JScrollPane();
        txt_IncomingOrders = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(370, 480));
        setMinimumSize(new java.awt.Dimension(370, 480));
        setPreferredSize(new java.awt.Dimension(370, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        pnl_register.setMaximumSize(new java.awt.Dimension(370, 480));
        pnl_register.setLayout(null);

        lbl_email1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_email1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email1.setText("Email:");
        pnl_register.add(lbl_email1);
        lbl_email1.setBounds(40, 140, 50, 22);
        pnl_register.add(txt_email1);
        txt_email1.setBounds(90, 140, 220, 30);

        lbl_register.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register.setText("Register");
        pnl_register.add(lbl_register);
        lbl_register.setBounds(110, 90, 170, 38);
        pnl_register.add(txt_password1);
        txt_password1.setBounds(90, 200, 220, 30);

        lbl_password1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_password1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password1.setText("Password:");
        pnl_register.add(lbl_password1);
        lbl_password1.setBounds(-10, 200, 110, 22);

        icon_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoReal.png"))); // NOI18N
        pnl_register.add(icon_logo1);
        icon_logo1.setBounds(0, 0, 80, 80);

        lbl_companyTitle1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle1.setText("Ivan's Z's Inc.");
        pnl_register.add(lbl_companyTitle1);
        lbl_companyTitle1.setBounds(140, 40, 180, 22);

        lbl_title1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_title1.setText("Quick Bite");
        pnl_register.add(lbl_title1);
        lbl_title1.setBounds(150, 10, 80, 22);

        icon_gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueskibidigradient.png"))); // NOI18N
        pnl_register.add(icon_gradient);
        icon_gradient.setBounds(0, 0, 370, 80);

        lbl_cardNumber.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lbl_cardNumber.setText("Card Number:");
        pnl_register.add(lbl_cardNumber);
        lbl_cardNumber.setBounds(0, 260, 90, 17);

        lbl_cvv.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_cvv.setText("CVV:");
        pnl_register.add(lbl_cvv);
        lbl_cvv.setBounds(40, 310, 50, 22);

        txt_cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cardNumberActionPerformed(evt);
            }
        });
        pnl_register.add(txt_cardNumber);
        txt_cardNumber.setBounds(90, 250, 220, 30);
        pnl_register.add(txt_cvv);
        txt_cvv.setBounds(90, 310, 80, 23);

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        pnl_register.add(btn_register);
        btn_register.setBounds(150, 370, 90, 23);

        lbl_loginPrompt.setText("Already have an account?");
        pnl_register.add(lbl_loginPrompt);
        lbl_loginPrompt.setBounds(80, 410, 151, 17);

        btn_toLoginScreen.setForeground(new java.awt.Color(0, 0, 255));
        btn_toLoginScreen.setText("Login");
        btn_toLoginScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_toLoginScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_toLoginScreenMouseClicked(evt);
            }
        });
        pnl_register.add(btn_toLoginScreen);
        btn_toLoginScreen.setBounds(220, 410, 31, 17);

        getContentPane().add(pnl_register);
        pnl_register.setBounds(0, 0, 370, 480);

        pnl_login.setMaximumSize(new java.awt.Dimension(370, 480));
        pnl_login.setPreferredSize(new java.awt.Dimension(370, 480));
        pnl_login.setLayout(null);

        lbl_registerPrompt.setText("New user?");
        pnl_login.add(lbl_registerPrompt);
        lbl_registerPrompt.setBounds(120, 350, 60, 17);

        btn_login.setText("Login");
        pnl_login.add(btn_login);
        btn_login.setBounds(150, 310, 60, 23);

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoReal.png"))); // NOI18N
        pnl_login.add(icon_logo);
        icon_logo.setBounds(0, 0, 80, 80);

        lbl_title.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_title.setText("Quick Bite");
        pnl_login.add(lbl_title);
        lbl_title.setBounds(150, 10, 80, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueskibidigradient.png"))); // NOI18N
        pnl_login.add(jLabel7);
        jLabel7.setBounds(0, 0, 370, 80);
        pnl_login.add(txt_email);
        txt_email.setBounds(110, 190, 214, 30);

        lbl_companyTitle.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle.setText("Ivan's Z's Inc.");
        pnl_login.add(lbl_companyTitle);
        lbl_companyTitle.setBounds(140, 40, 100, 22);
        pnl_login.add(txt_password);
        txt_password.setBounds(110, 260, 214, 30);

        lbl_login.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_login.setText("Login");
        pnl_login.add(lbl_login);
        lbl_login.setBounds(100, 90, 170, 38);

        txt_loginType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Administrator" }));
        pnl_login.add(txt_loginType);
        txt_loginType.setBounds(110, 150, 214, 23);

        btn_toRegisterScreen.setForeground(new java.awt.Color(0, 0, 255));
        btn_toRegisterScreen.setText("Register an account");
        btn_toRegisterScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_toRegisterScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_toRegisterScreenMouseClicked(evt);
            }
        });
        pnl_login.add(btn_toRegisterScreen);
        btn_toRegisterScreen.setBounds(180, 350, 110, 17);

        lbl_password.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText("Password:");
        pnl_login.add(lbl_password);
        lbl_password.setBounds(24, 260, 80, 22);

        lbl_email.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email.setText("Email:");
        pnl_login.add(lbl_email);
        lbl_email.setBounds(53, 190, 50, 30);

        getContentPane().add(pnl_login);
        pnl_login.setBounds(0, 0, 370, 480);

        pnl_customerHomeScreen.setMaximumSize(new java.awt.Dimension(370, 480));
        pnl_customerHomeScreen.setLayout(null);

        icon_logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoReal.png"))); // NOI18N
        pnl_customerHomeScreen.add(icon_logo2);
        icon_logo2.setBounds(0, 0, 80, 80);

        lbl_companyTitle2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle2.setText("Ivan's Z's Inc.");
        pnl_customerHomeScreen.add(lbl_companyTitle2);
        lbl_companyTitle2.setBounds(140, 40, 100, 22);

        lbl_title2.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_title2.setText("Quick Bite");
        pnl_customerHomeScreen.add(lbl_title2);
        lbl_title2.setBounds(150, 10, 80, 22);

        icon_gradient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueskibidigradient.png"))); // NOI18N
        pnl_customerHomeScreen.add(icon_gradient1);
        icon_gradient1.setBounds(0, 0, 370, 80);

        lbl_currentOrders.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_currentOrders.setText("Current Orders:");
        pnl_customerHomeScreen.add(lbl_currentOrders);
        lbl_currentOrders.setBounds(110, 110, 140, 20);

        lbl_newOrder.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_newOrder.setText("New Order:");
        pnl_customerHomeScreen.add(lbl_newOrder);
        lbl_newOrder.setBounds(130, 310, 110, 22);

        btn_newOrder.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btn_newOrder.setText("Place new order");
        pnl_customerHomeScreen.add(btn_newOrder);
        btn_newOrder.setBounds(110, 360, 140, 40);

        txt_orderDisplay.setColumns(20);
        txt_orderDisplay.setRows(5);
        pane_orderDisplay.setViewportView(txt_orderDisplay);

        pnl_customerHomeScreen.add(pane_orderDisplay);
        pane_orderDisplay.setBounds(40, 136, 270, 160);

        getContentPane().add(pnl_customerHomeScreen);
        pnl_customerHomeScreen.setBounds(0, 0, 370, 480);

        pnl_adminHomeScreen.setMaximumSize(new java.awt.Dimension(370, 480));
        pnl_adminHomeScreen.setLayout(null);

        icon_logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoReal.png"))); // NOI18N
        pnl_adminHomeScreen.add(icon_logo3);
        icon_logo3.setBounds(0, 0, 80, 80);

        lbl_companyTitle3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_companyTitle3.setText("Ivan's Z's Inc.");
        pnl_adminHomeScreen.add(lbl_companyTitle3);
        lbl_companyTitle3.setBounds(140, 40, 100, 22);

        lbl_title3.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_title3.setText("Quick Bite");
        pnl_adminHomeScreen.add(lbl_title3);
        lbl_title3.setBounds(150, 10, 80, 22);

        icon_gradient2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blueskibidigradient.png"))); // NOI18N
        pnl_adminHomeScreen.add(icon_gradient2);
        icon_gradient2.setBounds(0, 0, 370, 80);

        lbl_incomingOrders.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_incomingOrders.setText("Incoming Orders");
        pnl_adminHomeScreen.add(lbl_incomingOrders);
        lbl_incomingOrders.setBounds(120, 110, 130, 22);

        txt_IncomingOrders.setColumns(20);
        txt_IncomingOrders.setRows(5);
        pane_incomingOrders.setViewportView(txt_IncomingOrders);

        pnl_adminHomeScreen.add(pane_incomingOrders);
        pane_incomingOrders.setBounds(40, 150, 290, 130);

        getContentPane().add(pnl_adminHomeScreen);
        pnl_adminHomeScreen.setBounds(0, 0, 370, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Account information file
    File AccountFile = new File("Accounts.txt");
    //Account information arraylist (for searching and modifying the text file)
    ArrayList<Customer> AccountList = new ArrayList<>();
    
    private void txt_cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cardNumberActionPerformed

    }//GEN-LAST:event_txt_cardNumberActionPerformed

    private void btn_toRegisterScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_toRegisterScreenMouseClicked
        //When user clicks the prompt on the login screen, this takes them to the register screen
        pnl_register.setVisible(true); 
        pnl_login.setVisible(false);
    }//GEN-LAST:event_btn_toRegisterScreenMouseClicked

    private void btn_toLoginScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_toLoginScreenMouseClicked
        //When the user clicks the prompt on the register screen, this takes them to the login screen
        pnl_login.setVisible(true);
        pnl_register.setVisible(false);
    }//GEN-LAST:event_btn_toLoginScreenMouseClicked

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        //Input validation
        ValidateCard validator = new ValidateCard();
        
        //Checking for empty input fields
        if (txt_email1.getText().strip().isEmpty() || txt_password1.getText().strip().isEmpty() || txt_cardNumber.getText().strip().isEmpty() || txt_cvv.getText().strip().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please ensure all input fields are filled in.", "Error", 2);
        } else if (!txt_email1.getText().strip().contains(".") || !txt_email1.getText().strip().contains("@")) {
            //Checking if the email input contains a "." and a "@"
            JOptionPane.showMessageDialog(this, "Please ensure you have entered a valid email.", "Error", 2);
        } else if (!validator.ValidateCard(txt_cardNumber.getText(), txt_cvv.getText().strip())) {
            JOptionPane.showMessageDialog(this, "Please ensure you enter a valid credit/debit card number and CVV code.", "Error", 2);
        } else {
            try {
                AccountFile.createNewFile(); //Creates the accounts.txt file if it doesn't exist already
                if (AccountList.isEmpty()) { //If the account list is empty, read from the file
                    readFile();
                    if (AccountList.isEmpty()) { //If the account list is STILL empty, add the new user's info to the text file
                        
                    }  
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "There was an error: " + e, "Error!", 1);
            }
        }
    }//GEN-LAST:event_btn_registerActionPerformed
    
    public void readFile() { //Method for reading from the text file, and converting the raw data into customer instances
        
        try {
            if (!AccountFile.createNewFile()) { //If the account fails to create (Already existing), read from the file
                BufferedReader reader = new BufferedReader(new FileReader(AccountFile.getAbsoluteFile()));
                String line;
                
                while ((line = reader.readLine()) != null) {
                    String[] lineArray = line.split(","); //Splitting everything by commas
                    String email = lineArray[0];
                    String password = lineArray[1];
                    String cardNumber = lineArray[2];
                    String cvv = lineArray[3];
                    int points = Integer.parseInt(lineArray[4]);
                    Customer person = new Customer(email, password, cardNumber, cvv); //Constructor only takes these values
                    person.addPoints(points); //Adding customer's points to the default balance of zero
                    AccountList.add(person);
                }
                reader.close();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fatal error reading from accounts file.", "ERROR!", 2);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_newOrder;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel btn_toLoginScreen;
    private javax.swing.JLabel btn_toRegisterScreen;
    private javax.swing.JLabel icon_gradient;
    private javax.swing.JLabel icon_gradient1;
    private javax.swing.JLabel icon_gradient2;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel icon_logo1;
    private javax.swing.JLabel icon_logo2;
    private javax.swing.JLabel icon_logo3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_cardNumber;
    private javax.swing.JLabel lbl_companyTitle;
    private javax.swing.JLabel lbl_companyTitle1;
    private javax.swing.JLabel lbl_companyTitle2;
    private javax.swing.JLabel lbl_companyTitle3;
    private javax.swing.JLabel lbl_currentOrders;
    private javax.swing.JLabel lbl_cvv;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_email1;
    private javax.swing.JLabel lbl_incomingOrders;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_loginPrompt;
    private javax.swing.JLabel lbl_newOrder;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JLabel lbl_registerPrompt;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JLabel lbl_title2;
    private javax.swing.JLabel lbl_title3;
    private javax.swing.JScrollPane pane_incomingOrders;
    private javax.swing.JScrollPane pane_orderDisplay;
    private javax.swing.JPanel pnl_adminHomeScreen;
    private javax.swing.JPanel pnl_customerHomeScreen;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_register;
    private javax.swing.JTextArea txt_IncomingOrders;
    private javax.swing.JTextField txt_cardNumber;
    private javax.swing.JTextField txt_cvv;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JComboBox<String> txt_loginType;
    private javax.swing.JTextArea txt_orderDisplay;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_password1;
    // End of variables declaration//GEN-END:variables
}
