/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Ivan Lin and Noah Cummings
 */
public class register extends javax.swing.JPanel {
    JPanel mainPanel;
    
    /**
     * Creates new form register
     */
    public register(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_email1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_register = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_password1 = new javax.swing.JLabel();
        icon_logo1 = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        icon_gradient = new javax.swing.JLabel();
        lbl_cardNumber = new javax.swing.JLabel();
        lbl_cvv = new javax.swing.JLabel();
        txt_cardNumber = new javax.swing.JTextField();
        txt_cvv = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        lbl_loginPrompt = new javax.swing.JLabel();
        btn_toLoginScreen = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(370, 480));
        setLayout(null);

        lbl_email1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_email1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email1.setText("Email");
        add(lbl_email1);
        lbl_email1.setBounds(50, 130, 50, 22);
        add(txt_email);
        txt_email.setBounds(50, 160, 270, 30);

        lbl_register.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register.setText("Sign Up");
        add(lbl_register);
        lbl_register.setBounds(100, 90, 170, 38);
        add(txt_password);
        txt_password.setBounds(50, 230, 270, 30);

        lbl_password1.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_password1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password1.setText("Password");
        add(lbl_password1);
        lbl_password1.setBounds(47, 200, 90, 22);

        icon_logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quick_bite_logo_80x80.png"))); // NOI18N
        add(icon_logo1);
        icon_logo1.setBounds(0, 0, 80, 80);

        lbl_title1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lbl_title1.setText("Quick Bite");
        add(lbl_title1);
        lbl_title1.setBounds(130, 25, 130, 30);

        icon_gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinalGradient.png"))); // NOI18N
        add(icon_gradient);
        icon_gradient.setBounds(0, 0, 370, 80);

        lbl_cardNumber.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_cardNumber.setText("Card Number");
        add(lbl_cardNumber);
        lbl_cardNumber.setBounds(50, 270, 130, 22);

        lbl_cvv.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lbl_cvv.setText("CVV");
        add(lbl_cvv);
        lbl_cvv.setBounds(50, 340, 50, 22);

        txt_cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cardNumberActionPerformed(evt);
            }
        });
        add(txt_cardNumber);
        txt_cardNumber.setBounds(50, 300, 220, 30);
        add(txt_cvv);
        txt_cvv.setBounds(50, 370, 80, 21);

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        add(btn_register);
        btn_register.setBounds(150, 410, 90, 21);

        lbl_loginPrompt.setText("Already have an account?");
        add(lbl_loginPrompt);
        lbl_loginPrompt.setBounds(100, 440, 146, 15);

        btn_toLoginScreen.setForeground(new java.awt.Color(0, 0, 255));
        btn_toLoginScreen.setText("Login");
        btn_toLoginScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_toLoginScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_toLoginScreenMouseClicked(evt);
            }
        });
        add(btn_toLoginScreen);
        btn_toLoginScreen.setBounds(250, 440, 30, 15);
    }// </editor-fold>//GEN-END:initComponents
    
    //Account information file
    static File AccountFile = new File("Accounts.txt");
    //Account information arraylist (for searching and modifying the text file)
    public static ArrayList<Customer> AccountList = new ArrayList<>();
    public static Customer CurrentUser;                                             

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {                                             
        //Input validation
        ValidateCard validator = new ValidateCard();

        //Checking for empty input fields
        if (txt_email.getText().strip().isEmpty() || txt_password.getText().strip().isEmpty() || txt_cardNumber.getText().strip().isEmpty() || txt_cvv.getText().strip().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please ensure all input fields are filled in.", "Error", 2);
        } else if (!txt_email.getText().strip().contains(".") || !txt_email.getText().strip().contains("@")) {
            //Checking if the email input contains a "." and a "@"
            JOptionPane.showMessageDialog(this, "Please ensure you have entered a valid email.", "Error", 2);
        } else if (!validator.ValidateCard(txt_cardNumber.getText(), txt_cvv.getText().strip())) {
            JOptionPane.showMessageDialog(this, "Please ensure you enter a valid credit/debit card number and CVV code.", "Error", 2);
        } else {
            try {
                AccountFile.createNewFile(); //Creates the accounts.txt file if it doesn't exist already
                if (AccountList.isEmpty()) { //If the account list is empty, read from the file
                    readFile();
                    if (AccountList.isEmpty()) { //If the account list is STILL empty, add the new user's info to the arraylist
                        String email = txt_email.getText().strip();
                        String password = txt_password.getText().strip();
                        String cardNumber = txt_cardNumber.getText().strip();
                        String[] splitNumber = cardNumber.split(" "); //Formatting card number
                        cardNumber = String.join("", splitNumber);
                        String cvv = txt_cvv.getText().strip();
                        Customer newCustomer = new Customer(email, password, cardNumber, cvv);
                        CurrentUser = newCustomer;
                        AccountList.add(newCustomer);
                        writeFile(); 
                        JOptionPane.showMessageDialog(this, "Success! Account registered.");
                        
                        //Sending user to login screen
                        CardLayout cl = (CardLayout) mainPanel.getLayout();
                        cl.show(mainPanel, "login");
                    } else {
                        BinarySearch search = new BinarySearch();
                        if (search.search(AccountList, txt_email.getText())) {
                            JOptionPane.showMessageDialog(this, "Error, this email is already registered.", "Warning", 1);
                        } else {
                            String email = txt_email.getText().strip();
                            String password = txt_password.getText().strip();
                            String cardNumber = txt_cardNumber.getText().strip();
                            String[] splitNumber = cardNumber.split(" "); //Formatting card number
                            cardNumber = String.join("", splitNumber);
                            String cvv = txt_cvv.getText().strip();
                            Customer newCustomer = new Customer(email, password, cardNumber, cvv);
                            CurrentUser = newCustomer;
                            AccountList.add(newCustomer);
                            writeFile();
                            JOptionPane.showMessageDialog(this, "Success! Account registered.");
                            
                            //Sending user to login screen
                            CardLayout cl = (CardLayout) mainPanel.getLayout();
                            cl.show(mainPanel, "login");
                        }
                    }
                } else {
                    BinarySearch search = new BinarySearch();
                    if (search.search(AccountList, txt_email.getText().strip())) {
                        JOptionPane.showMessageDialog(this, "Error, this email is already registered.", "Warning", 1);
                    } else {
                        String email = txt_email.getText().strip();
                        String password = txt_password.getText().strip();
                        String cardNumber = txt_cardNumber.getText().strip();
                        String[] splitNumber = cardNumber.split(" "); //Formatting card number
                        cardNumber = String.join("", splitNumber);
                        String cvv = txt_cvv.getText().strip();
                        Customer newCustomer = new Customer(email, password, cardNumber, cvv);
                        CurrentUser = newCustomer;
                        AccountList.add(newCustomer);
                        writeFile();
                        JOptionPane.showMessageDialog(this, "Success! Account registered.");

                        //Sending user to login screen
                        CardLayout cl = (CardLayout) mainPanel.getLayout();
                        cl.show(mainPanel, "login");
                        
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "There was an error: " + e, "Error!", 1);
            }
        }
    }                                            

    private void btn_toLoginScreenMouseClicked(java.awt.event.MouseEvent evt) {                                               
        //When the user clicks the prompt on the register screen, this takes them to the login screen
        CardLayout cl = (CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "login");
    }                                              
       
    public void readFile() { //Method for reading from the text file, and converting the raw data into customer instances
        try {
            if (!AccountFile.createNewFile()) { //If the account fails to create (Already existing), read from the file
                BufferedReader reader = new BufferedReader(new FileReader(AccountFile.getAbsoluteFile()));
                String line;
                
                while ((line = reader.readLine()) != null) {
                    String[] lineArray = line.split(","); //Splitting everything by commas
                    String email = lineArray[0];
                    String password = lineArray[1];
                    String cardNumber = lineArray[2];
                    String cvv = lineArray[3];
                    int points = Integer.parseInt(lineArray[4]);
                    ArrayList <Integer> orderIDs = new ArrayList <>();
                    for(int i = 5; i < lineArray.length; i++){
                        orderIDs.add(Integer.parseInt(lineArray[i]));
                    }
                    Customer person = new Customer(email, password, cardNumber, cvv); //Constructor only takes these values
                    person.addPoints(points); //Adding customer's points to the default balance of zero
                    person.setOrderIDs(orderIDs);
                    AccountList.add(person);
                }
                reader.close();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fatal error reading from accounts file.", "ERROR!", 2);
        }
    }
    
    public void writeFile() {
        InsertionSort sort = new InsertionSort(); //Sorting array list with insertion sort 
        //Insertion sort is great for arrays that are almost entirely sorted
        sort.InsertionSort(AccountList);
        try {
            AccountFile.createNewFile();
            try (BufferedWriter deleter = new BufferedWriter(new FileWriter(AccountFile.getAbsolutePath()))) 
            {
                deleter.write("");
                deleter.close();
                BufferedWriter writer = new BufferedWriter(new FileWriter(AccountFile.getAbsolutePath(), true));
                
                for (int index = 0; index < AccountList.size(); index++) {
                    String writeLine = "";
                    writeLine += AccountList.get(index).getEmail() + ",";
                    writeLine += AccountList.get(index).getPassword() + ",";
                    writeLine += AccountList.get(index).getCardNumber() + ",";
                    writeLine += AccountList.get(index).getSecurityCode() + ",";
                    writeLine += AccountList.get(index).getPoints();
                    writeLine += AccountList.get(index).getOrderIDsString() + "\n";
                    writer.append(writeLine);
                }
                writer.close();
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "A fatal error occured: " + e, "ERROR!", 1);
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel btn_toLoginScreen;
    private javax.swing.JLabel icon_gradient;
    private javax.swing.JLabel icon_logo1;
    private javax.swing.JLabel lbl_cardNumber;
    private javax.swing.JLabel lbl_cvv;
    private javax.swing.JLabel lbl_email1;
    private javax.swing.JLabel lbl_loginPrompt;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JTextField txt_cardNumber;
    private javax.swing.JTextField txt_cvv;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
